[2024-08-11T21:00:08.220+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T21:00:08.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.export_data_to_db manual__2024-08-11T21:00:02.499935+00:00 [queued]>
[2024-08-11T21:00:08.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.export_data_to_db manual__2024-08-11T21:00:02.499935+00:00 [queued]>
[2024-08-11T21:00:08.234+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-11T21:00:08.239+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-08-11 21:00:02.499935+00:00
[2024-08-11T21:00:08.242+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=279) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-11T21:00:08.243+0000] {standard_task_runner.py:64} INFO - Started process 281 to run task
[2024-08-11T21:00:08.243+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather', 'export_data_to_db', 'manual__2024-08-11T21:00:02.499935+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpo66o5caa']
[2024-08-11T21:00:08.245+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask export_data_to_db
[2024-08-11T21:00:08.265+0000] {task_command.py:426} INFO - Running <TaskInstance: weather.export_data_to_db manual__2024-08-11T21:00:02.499935+00:00 [running]> on host 14d759344545
[2024-08-11T21:00:08.299+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T21:00:02.499935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-11T21:00:02.499935+00:00'
[2024-08-11T21:00:08.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T21:00:08.300+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T21:00:08.301+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/weather_to_db.py --date 2024-08-11 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-08-11T21:00:08.305+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T21:00:08.737+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-11T21:00:08.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T21:00:08.755+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather, task_id=export_data_to_db, run_id=manual__2024-08-11T21:00:02.499935+00:00, execution_date=20240811T210002, start_date=20240811T210008, end_date=20240811T210008
[2024-08-11T21:00:08.798+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T21:00:08.810+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T21:00:08.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
