[2024-08-12T01:19:56.009+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T01:19:56.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.export_data_to_db manual__2024-08-12T01:19:47.413206+00:00 [queued]>
[2024-08-12T01:19:56.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.export_data_to_db manual__2024-08-12T01:19:47.413206+00:00 [queued]>
[2024-08-12T01:19:56.023+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-12T01:19:56.028+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-08-12 01:19:47.413206+00:00
[2024-08-12T01:19:56.033+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-12T01:19:56.034+0000] {standard_task_runner.py:64} INFO - Started process 115 to run task
[2024-08-12T01:19:56.034+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather', 'export_data_to_db', 'manual__2024-08-12T01:19:47.413206+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpbkns_136']
[2024-08-12T01:19:56.036+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask export_data_to_db
[2024-08-12T01:19:56.056+0000] {task_command.py:426} INFO - Running <TaskInstance: weather.export_data_to_db manual__2024-08-12T01:19:47.413206+00:00 [running]> on host 230d4773b38e
[2024-08-12T01:19:56.105+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T01:19:47.413206+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T01:19:47.413206+00:00'
[2024-08-12T01:19:56.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T01:19:56.106+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-12T01:19:56.107+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/weather_to_db.py --date 2024-08-12 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-08-12T01:19:56.112+0000] {subprocess.py:86} INFO - Output:
[2024-08-12T01:19:56.750+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-12T01:19:56.751+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T01:19:56.763+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather, task_id=export_data_to_db, run_id=manual__2024-08-12T01:19:47.413206+00:00, execution_date=20240812T011947, start_date=20240812T011956, end_date=20240812T011956
[2024-08-12T01:19:56.804+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-12T01:19:56.814+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T01:19:56.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
