[2024-08-12T17:38:06.485+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T17:38:06.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.export_data_to_db manual__2024-08-12T17:37:47.003704+00:00 [queued]>
[2024-08-12T17:38:06.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.export_data_to_db manual__2024-08-12T17:37:47.003704+00:00 [queued]>
[2024-08-12T17:38:06.499+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-12T17:38:06.504+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-08-12 17:37:47.003704+00:00
[2024-08-12T17:38:06.509+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4823) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-12T17:38:06.511+0000] {standard_task_runner.py:64} INFO - Started process 4825 to run task
[2024-08-12T17:38:06.511+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather', 'export_data_to_db', 'manual__2024-08-12T17:37:47.003704+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpxcwxntzm']
[2024-08-12T17:38:06.513+0000] {standard_task_runner.py:91} INFO - Job 173: Subtask export_data_to_db
[2024-08-12T17:38:06.533+0000] {task_command.py:426} INFO - Running <TaskInstance: weather.export_data_to_db manual__2024-08-12T17:37:47.003704+00:00 [running]> on host b0294fd9f5f9
[2024-08-12T17:38:06.590+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T17:37:47.003704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T17:37:47.003704+00:00'
[2024-08-12T17:38:06.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T17:38:06.593+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-12T17:38:06.594+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/weather_to_db.py --date 2024-08-12 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-08-12T17:38:06.603+0000] {subprocess.py:86} INFO - Output:
[2024-08-12T17:38:10.593+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-12T17:38:10.599+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T17:38:10.659+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather, task_id=export_data_to_db, run_id=manual__2024-08-12T17:37:47.003704+00:00, execution_date=20240812T173747, start_date=20240812T173806, end_date=20240812T173810
[2024-08-12T17:38:10.719+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-12T17:38:10.752+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T17:38:10.754+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
